### 
POST http://localhost:4000/login
content-type: application/json

{
    "email":"test1@test.com",
    "password":"1234"
}
    

###

POST http://localhost:4000/signup
content-type: application/json

{
    "email":"test1@test.com",
    "nickName":"pingu1",
    "password":"1234"
}

###

POST http://localhost:4000/board
content-type: application/json

{
    "title":"hi",
    "main":"ok",
    "parentCategory":"front",
    "childCategory":"react"
}

###

GET http://localhost:4000/users
