const js = require('./js.png')
const jwt = require('./jwttoken.jpg')
const go = require('./go.png')
const fire = require('./fire.png')
const nodes = require('./Node.png')
const phps = require('./php.png')
const python = require('./python.png')
const reduxss = require('./redux.png')
const c = require('./C.png')
const kotlin = require ('./Kotlin.png')
const reacts = require ('./react.png')
const ruby = require ('./Ruby.png')
const css = require ('./css.png')
const docker = require ('./docker.png')
const expresss = require ('./express.png')
const nests = require ('./nest.png')
const nexts = require ('./next.png')
const sequelize = require ('./sequelize.png')
const spring = require('./spring.png')
const java = require('./Java.png')
const html = require('./HTML.png')


export const stackimage = [html,css,js,nodes,reacts,nexts,reduxss,expresss,nests,java,jwt,go,fire,phps,python,c,kotlin,ruby,docker,sequelize,spring];
  